[package]
name = "multi_use_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.15", features = ["cargo"] }
crypto = "0.5.1"
dialoguer = "0.10.4"
rand = "0.8.5"
