[package]
name = "mucli"
version = "0.1.0"
authors = ["DevYatsu"]
description = "A multi-purposes client line interface: mucli!"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.15", features = ["cargo"] }
custom_error = "1.9.2"
dialoguer = "0.10.4"
indicatif = "0.17.5"
rand = "0.8.5"
simplecrypt = "1.0.2"

[[bin]]
name = "mucli"  # The name of the binary executable (without file extension)
path = "src/main.rs"  # The path to the main file (entry point) for your CLI
