name: Build and Move to mucli_installation

on:
  push:
    branches:
      - main

jobs:
  build_and_move_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Move Executable
        run: mv target/release/mucli mucli_installation/mucli_linux

  build_and_move_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Move Windows Executable
        run: Move-Item target\release\mucli.exe mucli_installation\mucli_windows.exe

  build_and_move_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Move macOS Executable
        run: mv target/release/mucli mucli_installation/mucli_macos
